### ISSUE TITLE
Solr 5.x and configuration files not found

### ISSUE THREAD

**Issue by tloubrieu** [52North/OpenSensorSearch#51]
I have been able to build by updating the main pom.xml with the schema version:
  <sensorweb.schemas.version>2.0.0</sensorweb.schemas.version>

I have created the database schema on postgresql with script: service/src/main/resources/db/datamodel_v2.sql

I have installed and started a solr service in standalone in version 5.2.0 (4.4.0 was not deploying on my tomcat8) and I have created the core as shown in documentation. I only had to update:
in solrconfig.xml, commented section:
```
<!-- upgrade version 5.2
        <requestHandler name="/update/json" class="solr.JsonUpdateRequestHandler">
                <lst name="defaults">
                        <str name="stream.contentType">application/json</str>
                </lst>
        </requestHandler>
-->
```

in solrschema.xml:
```
  <filter class="solr.EdgeNGramFilterFactory" minGramSize="2"
                                        maxGramSize="15"/>
<!-- attribute remove for solr 5.2 -->
<!-- side="front" -->
```

When oss-service webapps is starting I have the following error:

```
15-Jun-2015 14:46:33.842 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /export/home/logiciels/apache-tomcat-8.0.23/webapps/oss-service.war
15-Jun-2015 14:46:49.673 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/export/home/logiciels/apache-tomcat-8.0.23/webapps/oss-service/WEB-INF/lib/slf4j-log4j12-1.5.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/export/home/logiciels/apache-tomcat-8.0.23/webapps/oss-service/WEB-INF/lib/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
SLF4J: The requested version 1.5.8 by your slf4j binding is not compatible with [1.6, 1.7]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
15-Jun-2015 14:46:50.015 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
15-Jun-2015 14:46:50.020 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/oss-service] startup failed due to previous errors
15-Jun-2015 14:46:50.061 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /export/home/logiciels/apache-tomcat-8.0.23/webapps/oss-service.war has finished in 16,218 ms
```

I don't know where I can find the container log.

However I am expecting that one issues is the configuration of the solr service ot be used.

In the home directory I have the following configuration files:
db.properties
org.n52.oss.service-sample.properties
sir.properties

From the documentation, "org.n52.oss.service-sample.properties" is considered, but I am not sure if "sir.properties" which contains configuration for solr services is considered.

Thanks very much,

Thomas

**Comment by nuest** [comment]
Hi Thomas! Thanks for your interest in the OpenSensorSearch project!

If you need to use a **newer Solr version**, you probably have to increase the version of the used client library (see in [this class](https://github.com/52North/OpenSensorSearch/blob/master/service/src/main/java/org/n52/sir/ds/solr/SolrConnection.java) how Solr is called from the [search handler](https://github.com/52North/OpenSensorSearch/blob/master/service/src/main/java/org/n52/sir/ds/solr/SOLRSearchSensorDAO.java) - I'm using only Solr Java classes here) in the pom of the service module: https://github.com/52North/OpenSensorSearch/blob/master/service/pom.xml#L208

Regarding the **container log file**, that should be the Tomcat log file in ``${catalina.base}/logs``, so check the files ``<your tomcat>/logs/catalina**.log`` and ``<your tomcat>/logs/localhost**.log``.

For details see https://tomcat.apache.org/tomcat-8.0-doc/logging.html

There should also be log files for the several OpenSensorSearch components in that directory.

Regarding the naming of the configuraiton files, please re-check with the documentation: https://github.com/52North/OpenSensorSearch#user-home-files

In you home directory, the file names must be ``org.n52.oss.service.sir.properties`` (with prefix), ``org.n52.oss.service.db.properties`` (with prefix) and ``org.n52.oss.service.properties`` (no "-sample")

**Comment by tloubrieu** [comment]
Thanks Daniel.
The server starts now properly when I use the right configuration files.
In addition I had to remove one log4j library (slf4j-log4j12-1.5.8.jar) which was in conflict with another (logback-classic-1.0.13.jar).

Tomorrow I'll add test records and see if I need to upgrade also the solr client libraries.

Thanks again !
