### ISSUE TITLE
OGC/Web service harvesting

### ISSUE THREAD

**Issue by tloubrieu** [52North/OpenSensorSearch#54]
Hello,

When I am trying to access the OGC harvesting function from menu (see screenshot) I am redirected on URL : http://ubisi54:8080/oss/#

What should be the proper URL for this function ? Do you have an idea why it doesn't work ?

![screenshot from 2015-07-21 14 25 08](https://cloud.githubusercontent.com/assets/4989802/8800595/6fc1db78-2fb4-11e5-85f8-c1acafceb71b.png)

**Comment by nuest** [comment]
Which version of OpenSensorSearch do you use?

**Comment by nuest** [comment]
The new harvesting functionality will be deprecated in future versions, see #49
